# Generated by Django 4.2.3 on 2025-03-23 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Account name')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account number')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank name')),
                ('account_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Bank account',
                'verbose_name_plural': 'Bank accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tripletex_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Tripletex ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('legacy_bank_account_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legacy bank account ID')),
                ('account_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account ID')),
                ('is_internal_transfer', models.BooleanField(default=False, verbose_name='Is internal transfer')),
                ('is_wage_transfer', models.BooleanField(default=False, verbose_name='Is wage transfer')),
                ('is_tax_transfer', models.BooleanField(default=False, verbose_name='Is tax transfer')),
                ('is_forbidden', models.BooleanField(default=False, verbose_name='Is forbidden')),
                ('should_process', models.BooleanField(default=True, verbose_name='Should process')),
                ('raw_data', models.JSONField(blank=True, help_text='Complete transaction data from the source system', null=True, verbose_name='Raw data')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Imported at')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.bankaccount', verbose_name='Bank account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', 'description'],
                'indexes': [models.Index(fields=['tripletex_id'], name='transaction_triplet_8373be_idx'), models.Index(fields=['date'], name='transaction_date_ad8c94_idx'), models.Index(fields=['legacy_bank_account_id'], name='transaction_legacy__67c6a1_idx'), models.Index(fields=['account_id'], name='transaction_account_36745c_idx'), models.Index(fields=['should_process'], name='transaction_should__af73ea_idx'), models.Index(fields=['is_internal_transfer'], name='transaction_is_inte_bb5d48_idx'), models.Index(fields=['is_wage_transfer'], name='transaction_is_wage_d5b1be_idx'), models.Index(fields=['is_tax_transfer'], name='transaction_is_tax__8539cf_idx'), models.Index(fields=['category'], name='transaction_categor_e3f163_idx')],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('source_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source file')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='transactions.bankaccount', verbose_name='Bank account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements', to='transactions.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Bank statement',
                'verbose_name_plural': 'Bank statements',
                'ordering': ['-date', 'description'],
                'indexes': [models.Index(fields=['date'], name='transaction_date_49fb09_idx'), models.Index(fields=['category'], name='transaction_categor_b001c6_idx'), models.Index(fields=['bank_account'], name='transaction_bank_ac_045963_idx')],
            },
        ),
    ]
