# Generated by Django 4.2.3 on 2025-03-23 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tripletex_id', models.CharField(max_length=255, unique=True, verbose_name='Tripletex ID')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account number')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('account_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account type')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Tripletex URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['account_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tripletex_id', models.CharField(max_length=255, unique=True, verbose_name='Tripletex ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('organization_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Tripletex URL')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.account', verbose_name='Ledger Account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.supplier', verbose_name='Supplier'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['supplier'], name='transaction_supplie_492ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ledger_account'], name='transaction_ledger__063a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tripletex_id'], name='transaction_triplet_b6836b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='transaction_name_e56c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tripletex_id'], name='transaction_triplet_4cae0a_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_number'], name='transaction_account_50a19d_idx'),
        ),
    ]
