# Generated by Django 4.2.3 on 2025-03-30 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_account_supplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankstatement',
            options={'ordering': ['-date'], 'verbose_name': 'Bank Statement', 'verbose_name_plural': 'Bank Statements'},
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements', to='transactions.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='source_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source File'),
        ),
    ]
