# Generated by Django 5.1.7 on 2025-03-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_bankstatement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account_id'], name='transaction_account_36745c_idx'),
        ),
    ]
