# Generated by Django 5.0.8 on 2024-06-05 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_bankstatement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('posting_id', models.IntegerField(help_text='The unique ID from Tripletex for this posting.', unique=True, verbose_name='Tripletex Posting ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('voucher_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Tripletex Voucher ID')),
                ('voucher_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Voucher Number')),
                ('voucher_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Voucher Type')),
                ('raw_data', models.JSONField(blank=True, help_text='Complete posting data from the Tripletex API', null=True, verbose_name='Raw data')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_postings', to='transactions.account', verbose_name='Account')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_postings', to='transactions.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Ledger Posting',
                'verbose_name_plural': 'Ledger Postings',
                'ordering': ['-date', '-posting_id'],
                'indexes': [models.Index(fields=['date'], name='ledger_post_date_idx'), models.Index(fields=['supplier'], name='ledger_post_supplier_idx'), models.Index(fields=['account'], name='ledger_post_account_idx')],
            },
        ),
    ]
