# Generated by Django 4.2.3 on 2025-04-16 17:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_add_ledger_posting_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySupplierMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Category-Supplier Mapping',
                'verbose_name_plural': 'Category-Supplier Mappings',
            },
        ),
        migrations.RenameIndex(
            model_name='ledgerposting',
            new_name='transaction_date_28e178_idx',
            old_name='ledger_post_date_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerposting',
            new_name='transaction_supplie_d97b3c_idx',
            old_name='ledger_post_supplier_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerposting',
            new_name='transaction_account_152497_idx',
            old_name='ledger_post_account_idx',
        ),
        migrations.AddField(
            model_name='categorysuppliermap',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_mappings', to='transactions.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='categorysuppliermap',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_mapping', to='transactions.supplier', verbose_name='Supplier'),
        ),
    ]
