# Generated by Django 4.2.3 on 2025-04-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_categorysuppliermap_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # This SQL will run to add the indexes directly
            sql='''
            -- Create the indexes with the new names directly, skipping the rename
            CREATE INDEX IF NOT EXISTS transaction_date_28e178_idx ON transactions_ledgerposting(date);
            CREATE INDEX IF NOT EXISTS transaction_supplie_d97b3c_idx ON transactions_ledgerposting(supplier_id);
            CREATE INDEX IF NOT EXISTS transaction_account_152497_idx ON transactions_ledgerposting(account_id);
            ''',
            # This SQL will run when rolling back the migration
            reverse_sql='''
            DROP INDEX IF EXISTS transaction_date_28e178_idx;
            DROP INDEX IF EXISTS transaction_supplie_d97b3c_idx;
            DROP INDEX IF EXISTS transaction_account_152497_idx;
            '''
        ),
    ]
