# Generated by Django 4.2.3 on 2025-04-16 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_fix_missing_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySupplierMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='supplier_mappings', to='transactions.category', verbose_name='Category')),
                ('supplier', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='category_mapping', to='transactions.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Category-Supplier Mapping',
                'verbose_name_plural': 'Category-Supplier Mappings',
            },
        ),
    ]
