# Generated by Django 4.2.3 on 2025-04-19 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_create_category_supplier_map_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Amount')),
                ('is_debit', models.BooleanField(default=True, help_text='True if this is a debit posting, False for credit', verbose_name='Is Debit')),
                ('posting_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Posting ID')),
                ('voucher_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Voucher ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='transactions.account', verbose_name='Account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_accounts', to='transactions.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Transaction Account',
                'verbose_name_plural': 'Transaction Accounts',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='accounts',
            field=models.ManyToManyField(related_name='related_transactions', through='transactions.TransactionAccount', to='transactions.account', verbose_name='Related Accounts'),
        ),
        migrations.AddIndex(
            model_name='transactionaccount',
            index=models.Index(fields=['transaction'], name='transaction_transac_4d143d_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionaccount',
            index=models.Index(fields=['account'], name='transaction_account_4a8f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionaccount',
            index=models.Index(fields=['posting_id'], name='transaction_posting_af96ac_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionaccount',
            index=models.Index(fields=['voucher_id'], name='transaction_voucher_d4c795_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionaccount',
            unique_together={('transaction', 'account', 'posting_id')},
        ),
    ]
