# Generated by Django 4.2.3 on 2025-04-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transactionaccount_transaction_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='closeGroup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Close Group'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['closeGroup'], name='transaction_closeGr_58b801_idx'),
        ),
    ]
