# Generated by Django 4.2.3 on 2025-04-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_account_closegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerposting',
            name='closeGroup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Close Group'),
        ),
        migrations.AddIndex(
            model_name='ledgerposting',
            index=models.Index(fields=['closeGroup'], name='transaction_closeGr_711706_idx'),
        ),
    ]
