# Generated by Django 4.2.3 on 2025-04-20 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_ledgerposting_closegroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='closeGroup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Close Group ID'),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='closeGroup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Close Group ID'),
        ),
        migrations.CreateModel(
            name='CloseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tripletex_id', models.CharField(max_length=255, unique=True, verbose_name='Tripletex ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('postings_count', models.IntegerField(default=0, verbose_name='Postings count')),
            ],
            options={
                'verbose_name': 'Close Group',
                'verbose_name_plural': 'Close Groups',
                'ordering': ['tripletex_id'],
                'indexes': [models.Index(fields=['tripletex_id'], name='transaction_triplet_94edd5_idx')],
            },
        ),
    ]
