# Generated by Django 4.2.3 on 2025-04-20 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_account_closegroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysuppliermap',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_maps', to='transactions.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='categorysuppliermap',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_maps', to='transactions.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='categorysuppliermap',
            unique_together={('supplier', 'category')},
        ),
        migrations.CreateModel(
            name='CloseGroupPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('close_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closegroup_postings', to='transactions.closegroup', verbose_name='Close Group')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closegroup_postings', to='transactions.ledgerposting', verbose_name='Posting')),
            ],
            options={
                'verbose_name': 'Close Group Posting',
                'verbose_name_plural': 'Close Group Postings',
            },
        ),
        migrations.AddField(
            model_name='closegroup',
            name='postings',
            field=models.ManyToManyField(related_name='close_groups', through='transactions.CloseGroupPosting', to='transactions.ledgerposting', verbose_name='Related Postings'),
        ),
        migrations.AddIndex(
            model_name='closegroupposting',
            index=models.Index(fields=['close_group'], name='transaction_close_g_7241da_idx'),
        ),
        migrations.AddIndex(
            model_name='closegroupposting',
            index=models.Index(fields=['posting'], name='transaction_posting_6b1434_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='closegroupposting',
            unique_together={('close_group', 'posting')},
        ),
    ]
