# Generated by Django 4.2.3 on 2025-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_categorysuppliermap_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly budget allocated for this category', max_digits=12, null=True, verbose_name='Monthly Budget'),
        ),
    ]
