# Generated by Django 4.2.3 on 2025-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_category_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly budget allocated for this category', max_digits=12, verbose_name='Budget'),
        ),
    ]
